const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const RI=Object.fromEntries(RESOURCES.map(r=>[r.id,r]));
const FI=Object.fromEntries(FAULTS.map(f=>[f.id,f]));
let current='superpod',profile='A3',tab='resource',faultFilter='all',includeChildren=false,activeFault=null;
let renderer;
const childResources=id=>RESOURCES.filter(r=>r.parent===id);
function descendantIDs(id){const out=new Set([id]);function next(p){for(let r of childResources(p)){if(out.has(r.id))continue;out.add(r.id);next(r.id);}}next(id);return out;}
function faultsFor(id,children=false){const ids=children?descendantIDs(id):new Set([id]);return FAULTS.filter(f=>f.resources.some(r=>ids.has(r)));}
const sourceLinks=ids=>`<div class="source-inline">${[...new Set(ids)].filter(x=>SOURCES[x]).map(x=>`<a href="${esc(SOURCES[x].url)}" target="_blank" rel="noopener noreferrer" title="${esc(SOURCES[x].title)}">${esc(x.toUpperCase())} ↗</a>`).join('')}</div>`;
function sourceCards(ids){return [...new Set(ids)].filter(x=>SOURCES[x]).map(x=>{let a=SOURCES[x];return `<div class="source-card"><a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.title)} ↗</a><small>${esc(a.scope)}</small><a class="source-url" href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.url)}</a></div>`;}).join('');}
const termRows=r=>r.terms.map(t=>`<div class="term-row">${esc(t)}</div>`).join('');
function renderNav(){let q=$('resource-search').value.trim().toLowerCase();let out='';GROUPS.forEach((g,i)=>{let items=RESOURCES.filter(r=>r.group===i&&(!q||[r.title,r.en,...r.terms,...faultsFor(r.id).map(f=>f.name)].join(' ').toLowerCase().includes(q)));if(!items.length)return;out+=`<details class="nav-group" open><summary><span class="group-num">0${i+1}</span>${esc(g)}</summary>`+items.map(r=>{let d=r.parent&&r.parent!=='cluster'&&(RI[r.parent]?.group===i)?1:0;let n=faultsFor(r.id).length;return `<button class="resource-btn ${current===r.id?'active':''}" data-resource="${r.id}" style="padding-left:${8+d*12}px" title="${esc(r.title)}：${n}条关联说明"><span class="dot"></span><span class="name">${esc(r.title)}</span>${n?`<span class="count">${n}</span>`:''}</button>`;}).join('')+'</details>';});$('resource-tree').innerHTML=out||'<div class="empty">没有匹配资源。可检索部件、缩写或故障名称。</div>';}
function makeCrumb(id){let chain=[],r=RI[id],seen=new Set();while(r&&!seen.has(r.id)){seen.add(r.id);chain.unshift(r);r=RI[r.parent];}return chain.map((r,i)=>`${i?'<span class="sep">/</span>':''}<button data-resource="${r.id}">${esc(r.title)}</button>`).join('');}
function selectResource(id,options={}){if(!RI[id])return;current=id;activeFault=options.fault||null;tab=options.tab||'resource';includeChildren=false;faultFilter='all';if(options.profile)profile=options.profile;if(!PROFILES[profile])profile='A3';$('profile-select').value=profile;let r=RI[id];$('scene-title').textContent=r.title;$('scene-en').textContent=r.en;$('breadcrumb').innerHTML=makeCrumb(id);$('detail-title').textContent=r.title;$('detail-en').textContent=r.en;$('detail-level').textContent=GROUPS[r.group];$('scene-profile').textContent=PROFILES[profile].short;$('scope-chip').textContent=['cq','queue','mac','buffers','core','dma','probe','os','filesystem'].includes(id)?'含逻辑示意 · 非实时数据':'结构示意 · 非实物CAD';
 let scene=createModel(r,profile);if(activeFault&&FI[activeFault]){const targets=new Set(FI[activeFault].resources),ids=new Set(scene.parts.filter(p=>targets.has(p.resource)).map(p=>p.id));for(let i=0;i<scene.vertices.length;i+=13){if(ids.has(scene.vertices[i+12])){scene.vertices[i+6]=scene.vertices[i+6]*.70+.93*.30;scene.vertices[i+7]=scene.vertices[i+7]*.70+.66*.30;scene.vertices[i+8]=scene.vertices[i+8]*.70+.28*.30;}}}renderer.setScene(scene);if(activeFault){$('explode').value='60';$('explode-value').value='60%';renderer.setExplosion(.60);}else if(options.resetExplosion){$('explode').value='0';$('explode-value').value='0%';renderer.setExplosion(0);}let note=scene.caption||r.scope+'。展开显示各部件位置，实际内部布局以对应产品文档为准。';$('scene-note').textContent=(activeFault?'暖色部件表示该条故障的关联资源，不表示当前告警。':'')+note;
 let kids=childResources(id),labelIDs=[...new Set(scene.labels.map(p=>p.resource))].filter(x=>RI[x]&&x!==id),links=[...new Set([...kids.map(r=>r.id),...labelIDs])].slice(0,10);$('part-links').innerHTML=links.map(x=>`<button data-resource="${x}">${esc(RI[x].title.replace('与',' / '))} <span aria-hidden="true">↗</span></button>`).join('')||`<button data-resource="${r.parent||'cluster'}">← 返回上层资源</button>`;
 renderNav();renderPanel();$('nav').classList.remove('mobile-open');if(options.hash!==false){let h=`resource=${encodeURIComponent(id)}&profile=${encodeURIComponent(profile)}`+(activeFault?`&fault=${activeFault}`:'');try{history.replaceState(null,'','#'+h);}catch(e){}}
 window.__atlasState={resource:current,profile,parts:scene.parts.length,vertices:scene.vertices.length/13,gl:!!renderer.gl};
}
const FAULT_TERMS={
 'ECC':'Error Correcting Code，纠错码；利用冗余校验发现并在能力范围内纠正数据错误。',
 'HBM':'High Bandwidth Memory，高带宽内存；加速器封装旁的堆叠内存。',
 'NPU':'Neural Network Processing Unit，神经网络处理单元。',
 'CPU':'Central Processing Unit，中央处理器。',
 'GPU':'Graphics Processing Unit，图形处理单元，也用于大规模并行计算。',
 'MCE':'Machine Check Exception，机器检查异常；须核对实际处理器架构和错误上报机制。',
 'AER':'Advanced Error Reporting，PCIe高级错误报告；与芯片内部健康汇总不是同一个概念。',
 'PCIe':'Peripheral Component Interconnect Express，高速串行设备互联总线。',
 'PFC':'Priority-based Flow Control，基于优先级的流量控制，通过暂停帧反压相邻发送端。',
 'CFC':'Credit-based Flow Control，基于信用的流量控制，按接收缓存的信用授权发送。',
 'CQE':'Completion Queue Entry，完成队列项，记录工作请求的完成结果。',
 'CQ':'Completion Queue，完成队列，保存可供软件处理的完成记录。',
 'QP':'Queue Pair，队列对；RDMA通信端点使用的发送/接收队列抽象。',
 'RDMA':'Remote Direct Memory Access，远程直接内存访问。',
 'HCCS':'Huawei Cache Coherence System，华为缓存一致性系统；此处指相关高速互联。',
 'MAC':'Media Access Control，介质访问控制；MAC地址用于以太网链路层寻址。',
 'ARP':'Address Resolution Protocol，地址解析协议，用于IPv4邻居地址解析。',
 'ND':'Neighbor Discovery，IPv6邻居发现，包含地址解析等功能。',
 'IP':'Internet Protocol，互联网协议；IP地址属于网络层地址。',
 'FEC':'Forward Error Correction，前向纠错，用冗余编码提高链路抗误码能力。',
 'CRC':'Cyclic Redundancy Check，循环冗余校验，用于检测传输数据错误。',
 'MTU':'Maximum Transmission Unit，最大传输单元，规定一次传输支持的数据大小边界。',
 'ECN':'Explicit Congestion Notification，显式拥塞通知，用标记反馈拥塞。',
 'CNP':'Congestion Notification Packet，拥塞通知报文；在相关RoCE拥塞控制方案中反馈给发送端。',
 'NVMe':'Non-Volatile Memory Express，非易失性内存高速接口规范，常用于SSD访问。',
 'SSD':'Solid-State Drive，固态硬盘。',
 'DRAM':'Dynamic Random Access Memory，动态随机存取存储器。',
 'SRAM':'Static Random Access Memory，静态随机存取存储器，常用于片内缓存等区域。',
 'DIMM':'Dual In-line Memory Module，双列直插内存模块。',
 'OOM':'Out Of Memory，内存不足；可能触发进程分配失败或系统内存回收/终止机制。',
 'UPS':'Uninterruptible Power Supply，不间断电源。',
 'PDU':'Power Distribution Unit，配电单元。',
 'PSU':'Power Supply Unit，设备电源模块。',
 'VRM':'Voltage Regulator Module，电压调节模块，为芯片提供所需电压。',
 'BMC':'Baseboard Management Controller，基板管理控制器，提供带外管理。'
};
function faultTerms(f){let text=[f.name,f.mechanism,...f.evidence,f.caution].join(' '),terms=Object.keys(FAULT_TERMS).filter(k=>new RegExp('(^|[^A-Za-z])'+k+'([^A-Za-z]|$)').test(text));if(!terms.length)return '';return '<details class="fault-terms"><summary>术语解释 · '+terms.map(esc).join(' / ')+'</summary>'+terms.map(k=>'<div class="term-row"><strong>'+esc(k)+'</strong> · '+esc(FAULT_TERMS[k])+'</div>').join('')+'</details>';}
function faultCard(f,open=false){let val=v=>v===null?'未提供':v;let field=(k,v,span=false)=>`<div class="field ${span?'span2':''}"><span class="k">${k}</span><span class="v ${v===null?'unknown':v==='开启'?'on':v==='关闭'?'off':''}">${esc(val(v))}</span></div>`;
 return `<details class="fault-card ${open?'focus':''}" data-fault-card="${f.id}" id="fault-${f.id}" ${open?'open':''}><summary><div><div class="fault-title">${esc(f.name)}</div><div class="fault-tags"><span>${esc(f.id)} · ${esc(f.domain)}</span><span class="kind">${esc(f.kind)}</span>${f.origin==='补充案例'?'<span class="extra">补充案例</span>':''}</div></div></summary><div class="fault-body"><h4>现象与产生机制</h4><p>${esc(f.mechanism)}</p>${faultTerms(f)}${f.chain?.length?`<div class="mini-chain">${f.chain.map((v,i)=>`<div class="chain-step"><span class="idx">0${i+1}</span>${esc(v)}</div>`).join('')}</div><p class="lead-note">可能的因果路径，用于解释机制，不是已发生事件的诊断结论。</p>`:''}<h4>判断时需要的证据</h4>${f.evidence.map(x=>`<div class="evidence-row">${esc(x)}</div>`).join('')}<div class="fault-caution">${esc(f.caution)}</div><h4>相关资源</h4><div class="part-links">${f.resources.filter(x=>RI[x]).map(x=>`<button data-locate="${f.id}" data-target="${x}">${esc(RI[x].title)} ↗</button>`).join('')}</div><p class="lead-note" style="margin-top:12px">公开版本只保留故障名称、机理与资源关联，不发布原始环境的开关、恢复配置和修改时间。</p><h4>来源范围</h4><p class="lead-note">名称${f.origin==='收录条目'?'为收录条目；':'为补充场景；'}下列公开资料支持机制、术语或产品背景，不代表已核实该平台专有告警码或阈值。</p>${sourceLinks(f.sources)}</div></details>`;
}
function renderFaults(r){let fs=faultsFor(r.id,includeChildren),filtered=fs.filter(f=>faultFilter==='all'||(faultFilter==='user'?f.origin==='收录条目':f.origin==='补充案例'));return `<div class="snapshot-alert">这里显示可能关联的故障知识，不是当前设备告警。${includeChildren?'包含下属资源；':'按本资源直接关联；'}收录条目与补充案例分开标注。</div><div class="fault-filters"><button data-fault-filter="all" class="${faultFilter==='all'?'selected':''}">全部 ${fs.length}</button><button data-fault-filter="user" class="${faultFilter==='user'?'selected':''}">原始 ${fs.filter(f=>f.origin==='收录条目').length}</button><button data-fault-filter="extra" class="${faultFilter==='extra'?'selected':''}">补充 ${fs.filter(f=>f.origin==='补充案例').length}</button>${childResources(r.id).length?`<button id="include-children" class="${includeChildren?'selected':''}">${includeChildren?'✓ ':''}含下属资源</button>`:''}</div>${filtered.length?filtered.map(f=>faultCard(f,f.id===activeFault)).join(''):'<div class="empty">清单中没有直接归属于此资源的记录。可展开下属部件，或在故障目录中按平面检索。</div>'}`;}
function renderPanel(){let r=RI[current],n=faultsFor(current).length;$('fault-tab-count').textContent=n;document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});let html='';
 if(tab==='resource'){let fs=faultsFor(current);html=`<p class="lead">${esc(r.lead)}</p>${r.paras.map(t=>`<p>${esc(t)}</p>`).join('')}<div class="section-head">名称与缩写</div>${termRows(r)}${fs.length?`<div class="section-head"><span>展开此资源时关注</span><button class="quiet" data-tab="faults" style="font-size:10px;padding:2px 5px">全部 ${fs.length} 条 →</button></div>${fs.slice(0,4).map(f=>`<button class="use-link" data-open-fault="${f.id}"><span class="count">${esc(f.id)}</span>${esc(f.name)}<span class="right">↗</span></button>`).join('')}`:''}<div class="section-head">结构范围与来源</div><p class="lead-note">${esc(r.scope)}。物理资源、协议状态和管理系统观测对象不混为一层。</p>${sourceLinks(r.sources)}`;
 }else if(tab==='protocol'){html=`<p class="lead">资源、接口与协议分别回答“在哪里”“怎样连接”“如何交换信息”。</p>${r.protocol.map((t,i)=>`<div class="protocol-step"><span class="eyebrow">0${i+1}</span><br>${esc(t)}</div>`).join('')}<div class="section-head">缩写与术语</div>${termRows(r)}${['queue','busport','nic','cq','ethport','npu_port'].includes(r.id)?communicationNotes(r.id):''}<div class="callout">同一种光纤或连接器外形，不能证明它承载相同协议。先确认端点、产品版本和网络平面，再解释错误码与指标。</div>${sourceLinks(r.sources)}`;
 }else if(tab==='faults')html=renderFaults(r);
 else if(tab==='compare'){html=`<div class="compare-label">ARCHITECTURE COMPARISON</div><p class="lead">${esc(r.compare)}</p><div class="compare-box"><div class="compare-label">HUAWEI · 昇腾</div><p>以具体Atlas服务器和SuperPoD产品为边界。HCCS（Huawei Cache Coherence System，华为缓存一致性系统）、灵衢UnifiedBus与基于以太网的互联位于不同职责层。</p></div><div class="compare-box"><div class="compare-label">NVIDIA · 固定对照 GB200 NVL72</div><p>GB200 NVL72采用72颗GPU与36颗Grace CPU组成的液冷机架。NVLink是设备紧耦合互联；跨域网络可以采用以太网或InfiniBand，不能把所有链路统一叫NVLink。</p></div><p class="lead-note">性能对比需要对齐精度、带宽方向、互联域、模型和工作负载。本网站不按芯片数量给出性能排名，也不把一方的专有故障码移植到另一方。</p><div class="section-head">当前产品边界</div>${profileContent(false)}${sourceLinks([...r.sources,'a3','nv72'])}`;
 }else if(tab==='sources'){let ids=[...r.sources,...faultsFor(current).flatMap(f=>f.sources)];html=`<p class="lead">资源说明与故障原理可以回到来源核对。</p><p>收录条目保留故障名称与所属平面，不包含原始环境配置；公开资料用于解释术语与一般机制。专有规则条件、阈值、数值型错误码没有提供时，不补造。</p>${sourceCards(ids)}<div class="section-head">图形与产品边界</div><p class="lead-note">本站模型由几何部件构建。机柜级规模以所选公开实例标注；CPU/NPU内部、槽位、散热器、板卡和线缆为功能示意，不是实物测绘或供应商CAD。</p>`;}
 $('detail-content').innerHTML=html;$('detail-content').scrollTop=0;if(activeFault&&tab==='faults')requestAnimationFrame(()=>{let e=document.querySelector(`[data-fault-card="${activeFault}"]`),sc=$('detail-content');if(e&&sc.scrollHeight>sc.clientHeight){sc.scrollTop=e.offsetTop-sc.offsetTop-10;}});}
function communicationNotes(id){let pfc='PFC · Priority-based Flow Control，基于优先级的流量控制：拥塞时暂停相邻链路上的特定优先级。',cfc='CFC · Credit-based Flow Control，基于信用的流量控制：按接收侧可用缓存信用授权发送。PFC暂停和CFC信用耗尽/循环等待不能混写。',cqe='CQ · Completion Queue，完成队列；CQE · Completion Queue Entry，完成队列项。CQE报告请求完成状态；出错时要结合操作类型、端点及具体完成码，不等于网卡已损坏。';return `<div class="section-head">容易混淆的通信概念</div><p>${esc(pfc)}</p><p>${esc(cfc)}</p><p>${esc(cqe)}</p>${sourceLinks(['pfc','cfc','rdma'])}`;}
function profileContent(withTitle=true){let p=PROFILES[profile];return `${withTitle?`<h3 style="margin-top:0">${esc(p.title)}</h3>`:''}<p style="font-size:13px;line-height:1.9;color:#a8c1d1">${esc(p.notes)}</p><div class="spec-grid">${p.specs.map(([k,v])=>`<div class="spec"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('')}</div>${sourceLinks(p.sources)}`;}
function openFault(id,target){let f=FI[id];if(!f)return;closeModal();selectResource(target||f.resources[0],{fault:id,tab:'faults'});if(window.innerWidth<=1000)$('detail-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
function openModal(type){$('modal').hidden=false;$('modal').dataset.type=type;$('modal-card').classList.toggle('narrow',type!=='catalog');document.body.style.overflow='hidden';$('modal-title').textContent=type==='catalog'?'故障目录与资源定位':type==='profile'?'产品边界与结构口径':'结构、数据与操作说明';$('modal-subtitle').textContent=type==='catalog'?'按平面保留收录条目，点击故障即可定位三维部件。':type==='profile'?'产品级已知事实与通用部件示意分开呈现。':'静态离线站点；不会连接或修改任何设备。';
 if(type==='catalog'){$('modal-controls').hidden=false;$('modal-controls').innerHTML=`<input id="fault-search" placeholder="搜索：HBM、CFC、光链路、CQE…" aria-label="搜索故障"><select id="domain-filter" aria-label="筛选网络平面"><option value="all">所有领域</option>${[...new Set(FAULTS.map(f=>f.domain))].map(d=>`<option>${esc(d)}</option>`).join('')}</select><select id="origin-filter" aria-label="筛选原始或补充"><option value="all">原始＋补充</option><option>收录条目</option><option>补充案例</option></select>`;for(let id of ['fault-search','domain-filter','origin-filter'])$(id).addEventListener(id==='fault-search'?'input':'change',renderCatalog);renderCatalog();$('modal-footer').innerHTML='<span>73条收录条目 · 65个不同名称 · 22条补充案例</span><button id="export-data">导出完整JSON</button>';
 }else{$('modal-controls').hidden=true;$('modal-footer').innerHTML='<span>来源页若要求登录，已在来源范围中注明；未提供专有参数不推定。</span>';$('modal-body').innerHTML=type==='profile'?profileContent():`<p class="lead">拖动场景旋转，滚轮缩放；点击实物部件或标签进入下层，使用展开滑块分离组件。</p><div class="section-head">阅读故障</div><p>右侧“故障”显示现象、机制、最小判断证据和容易误判的边界。同名故障跨越不同平面时，知识记录分别保留。</p><div class="section-head">公开数据范围</div><p>此版本保留故障知识和资源关联，移除原始环境的生成开关、恢复策略、规则入口及修改时间。没有设备执行功能，也没有实时监控连接。</p><div class="section-head">模型边界</div><p>本站使用可旋转的WebGL三维模型，故障计数表示知识记录关联数量，不表示活跃告警数或故障严重度。模型中的HBM层数、计算核心数量、端口数和槽位仅用于结构解释。</p><div class="section-head">版本与数据</div><p>公开资料访问口径为2026-09-22。源码、故障知识与来源保存在本目录。脚本全部随站点提供，不依赖外部 CDN 或设备接口。</p><button id="all-sources">查看全部来源链接</button>`;}
 setTimeout(()=>$('modal-close').focus(),0);}
function renderCatalog(){let q=$('fault-search').value.toLowerCase(),domain=$('domain-filter').value,origin=$('origin-filter').value;let fs=FAULTS.filter(f=>(domain==='all'||f.domain===domain)&&(origin==='all'||f.origin===origin)&&[f.name,f.id,f.kind,f.mechanism,...f.resources.map(x=>RI[x]?.title||x)].join(' ').toLowerCase().includes(q));$('modal-body').innerHTML=`<p class="lead-note" style="margin:0 0 7px">匹配 ${fs.length} 条。仅展示故障知识与资源关联，不包含实际环境的开关状态。</p><div class="fault-table-head"><span>编号</span><span>故障与观测类别</span><span>领域</span><span>关联资源</span><span>定位</span></div>${fs.map(f=>`<div class="fault-table-row"><span class="id">${f.id}</span><div><button class="fault-link" data-locate="${f.id}">${esc(f.name)}</button><small>${esc(f.kind)} · ${f.origin==='收录条目'?'收录条目':'补充案例'}</small></div><span class="hide-mobile">${esc(f.domain)}</span><span class="hide-mobile" style="font-size:11px;color:#adbfcc">${f.resources.length} 个</span><button class="jump" data-locate="${f.id}">定位资源 ↗</button></div>`).join('')}`;}
function closeModal(){$('modal').hidden=true;document.body.style.overflow='';}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2800);}
function exportData(){let blob=new Blob([JSON.stringify({description:'只读故障知识与资源映射；已移除原始环境配置，不是设备实时状态',faults:FAULTS,resources:RESOURCES,sources:SOURCES},null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='算力资源故障映射.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function readRoute(){let params=new URLSearchParams(location.hash.slice(1)),r=params.get('resource'),p=params.get('profile'),f=params.get('fault');if(p&&PROFILES[p])profile=p;selectResource(r&&RI[r]?r:'superpod',{fault:f&&FI[f]?f:null,tab:f&&FI[f]?'faults':'resource',hash:false});}
function start(){renderer=new AtlasRenderer($('scene-canvas'),$('labels'),id=>{if(RI[id]){if(id===current){toast('已在该资源层；使用下方部件入口继续展开');return;}selectResource(id);}});window.__atlasRenderer=renderer;window.__atlasSelect=selectResource;window.__atlasFault=openFault;window.__atlasData={resources:RESOURCES,faults:FAULTS,profiles:PROFILES,sources:SOURCES};$('render-status').textContent=renderer.gl?'● WEBGL 3D':'● 3D 投影回退';$('profile-select').innerHTML=Object.entries(PROFILES).sort((a,b)=>['A2','A3','A5','950','NV'].indexOf(a[0])-['A2','A3','A5','950','NV'].indexOf(b[0])).map(([k,v])=>`<option value="${k}">${esc(v.short)}</option>`).join('');
 $('resource-search').addEventListener('input',renderNav);$('profile-select').addEventListener('change',e=>{profile=e.target.value;selectResource(current,{profile,tab});});$('explode').addEventListener('input',e=>{renderer.setExplosion(Number(e.target.value)/100);$('explode-value').value=e.target.value+'%';});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.resource){selectResource(b.dataset.resource);return;}if(b.dataset.tab){tab=b.dataset.tab;renderPanel();return;}if(b.dataset.openFault){activeFault=b.dataset.openFault;tab='faults';renderPanel();return;}if(b.dataset.locate){openFault(b.dataset.locate,b.dataset.target);return;}if(b.dataset.faultFilter){faultFilter=b.dataset.faultFilter;renderPanel();return;}if(b.dataset.view){renderer.view(b.dataset.view);return;}switch(b.id){case 'zoom-in':renderer.zoom(.82);break;case 'zoom-out':renderer.zoom(1.22);break;case 'reset-scene':renderer.view('iso');$('explode').value=0;$('explode-value').value='0%';renderer.setExplosion(0);break;case 'open-catalog':openModal('catalog');break;case 'open-help':openModal('help');break;case 'profile-info':openModal('profile');break;case 'modal-close':closeModal();break;case 'nav-toggle':$('nav').classList.toggle('mobile-open');break;case 'include-children':includeChildren=!includeChildren;renderPanel();break;case 'export-data':exportData();break;case 'all-sources':$('modal-title').textContent='公开参考资料';$('modal-body').innerHTML=sourceCards(Object.keys(SOURCES));break;}});
 $('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('nav').classList.remove('mobile-open');}if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();openModal('catalog');setTimeout(()=>$('fault-search').focus(),30);}});window.addEventListener('hashchange',readRoute);readRoute();}
start();
