/* Small, dependency-free WebGL renderer. All dimensions are illustrative. */
const V3={add:(a,b)=>a.map((v,i)=>v+b[i]),sub:(a,b)=>a.map((v,i)=>v-b[i]),mul:(a,s)=>a.map(v=>v*s),dot:(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{let d=Math.hypot(...a)||1;return a.map(v=>v/d)}};
function perspective(fov,aspect,n,f){let q=1/Math.tan(fov/2);return [q/aspect,0,0,0,0,q,0,0,0,0,(f+n)/(n-f),-1,0,0,2*f*n/(n-f),0];}
function lookAt(eye,target){let z=V3.norm(V3.sub(eye,target)),x=V3.norm(V3.cross([0,1,0],z)),y=V3.cross(z,x);return [x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V3.dot(x,eye),-V3.dot(y,eye),-V3.dot(z,eye),1];}
function m4mul(a,b){let o=[];for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[r+4]*b[c*4+1]+a[r+8]*b[c*4+2]+a[r+12]*b[c*4+3];return o;}
const hexRGB=s=>{s=s.replace('#','');return [0,2,4].map(i=>parseInt(s.slice(i,i+2),16)/255);};
class GeometryScene{
 constructor(){this.parts=[];this.vertices=[];this.labels=[];this.extent=10;this.target=[0,1,0];this.caption='';}
 triangle(a,b,c,color,explode,id){const n=V3.norm(V3.cross(V3.sub(b,a),V3.sub(c,a)));for(let v of [a,b,c])this.vertices.push(...v,...n,...color,...explode,id);}
 register(pos,size,col,opts={}){let part={id:this.parts.length+1,pos,size,col,ex:opts.ex||[0,0,0],...opts};part.ex=Array.isArray(part.ex)&&part.ex.length===3?part.ex:[0,0,0];this.parts.push(part);if(opts.label)this.labels.push(part);return part;}
 box(pos,size,col,opts={}){let p=this.register(pos,size,col,opts),c=hexRGB(col),[x,y,z]=pos,[w,h,d]=size.map(v=>v/2);let v=[[x-w,y-h,z-d],[x+w,y-h,z-d],[x+w,y+h,z-d],[x-w,y+h,z-d],[x-w,y-h,z+d],[x+w,y-h,z+d],[x+w,y+h,z+d],[x-w,y+h,z+d]];let faces=[[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]];for(let f of faces){this.triangle(v[f[0]],v[f[1]],v[f[2]],c,p.ex,p.id);this.triangle(v[f[0]],v[f[2]],v[f[3]],c,p.ex,p.id);}return p;}
 rod(a,b,r,col,opts={}){const pos=V3.mul(V3.add(a,b),.5),size=a.map((v,i)=>Math.abs(v-b[i])+r*2),p=this.register(pos,size,col,opts),c=hexRGB(col),axis=V3.norm(V3.sub(b,a));let u=V3.norm(V3.cross(axis,Math.abs(axis[1])>.9?[1,0,0]:[0,1,0])),v=V3.cross(axis,u),N=opts.segments||10;for(let i=0;i<N;i++){let a0=i/N*Math.PI*2,a1=(i+1)/N*Math.PI*2;let off=t=>V3.add(V3.mul(u,Math.cos(t)*r),V3.mul(v,Math.sin(t)*r));let aa=V3.add(a,off(a0)),ab=V3.add(a,off(a1)),ba=V3.add(b,off(a0)),bb=V3.add(b,off(a1));this.triangle(aa,ba,bb,c,p.ex,p.id);this.triangle(aa,bb,ab,c,p.ex,p.id);this.triangle(a,aa,ab,c,p.ex,p.id);this.triangle(b,bb,ba,c,p.ex,p.id);}return p;}
 path(points,r,col,opts={}){for(let i=1;i<points.length;i++)this.rod(points[i-1],points[i],r,col,{...opts,label:opts.label&&i===1});}
 grid(w=16){this.box([0,-.20,0],[w,.22,w],'#111e2d',{pick:false});for(let i=-w/2;i<=w/2;i+=1){this.box([i,-.082,0],[.014,.006,w],'#233447',{pick:false});this.box([0,-.082,i],[w,.006,.014],'#233447',{pick:false});}}
}
class AtlasRenderer{
 constructor(canvas,labelLayer,onPick){this.canvas=canvas;this.labelLayer=labelLayer;this.onPick=onPick;this.yaw=.67;this.pitch=.52;this.explode=0;this.wantExplode=0;this.distance=14;this.target=[0,1,0];this.selected=0;this.drag=null;this.moved=false;this.dirty=true;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'low-power'});if(!this.gl){canvas.setAttribute('data-fallback','true');this.ctx=canvas.getContext('2d');this.reduced=true;}else this.initGL();
 canvas.addEventListener('pointerdown',e=>{this.drag={x:e.clientX,y:e.clientY,ox:e.clientX,oy:e.clientY};this.moved=false;canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!this.drag)return;let dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(Math.hypot(e.clientX-this.drag.ox,e.clientY-this.drag.oy)>5)this.moved=true;this.yaw-=dx*.006;this.pitch=Math.max(.12,Math.min(1.47,this.pitch+dy*.006));this.drag.x=e.clientX;this.drag.y=e.clientY;this.dirty=true;});
 canvas.addEventListener('pointerup',e=>{if(this.drag&&!this.moved){let r=canvas.getBoundingClientRect();this.pick(e.clientX-r.left,e.clientY-r.top);}this.drag=null;});
 canvas.addEventListener('pointercancel',()=>this.drag=null);
 canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom(Math.exp(e.deltaY*.001));},{passive:false});
 new ResizeObserver(()=>{this.resize();this.dirty=true;}).observe(canvas);this.resize();this.loop();
 }
 initGL(){let g=this.gl;const vs=`attribute vec3 aPos,aNormal,aColor,aEx;attribute float aId;uniform mat4 uVP;uniform float uExplode,uSelected;varying vec3 vColor,vNormal,vPos;void main(){vec3 p=aPos+aEx*uExplode;gl_Position=uVP*vec4(p,1.);vNormal=aNormal;vPos=p;vColor=aColor;if(abs(aId-uSelected)<.3&&uSelected>0.)vColor=mix(aColor,vec3(.98,.73,.33),.42);}`;
 const fs=`precision mediump float;varying vec3 vColor,vNormal,vPos;void main(){vec3 n=normalize(vNormal);vec3 key=normalize(vec3(-.55,.9,.6));float light=.47+.46*max(dot(n,key),0.)+.15*max(dot(n,normalize(vec3(.7,.4,-.5))),0.);vec3 color=vColor*light;float fog=smoothstep(30.,65.,length(vPos));gl_FragColor=vec4(mix(color,vec3(.035,.064,.098),fog*.8),1.);}`;
 const compile=(type,text)=>{let s=g.createShader(type);g.shaderSource(s,text);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));return s;};this.program=g.createProgram();g.attachShader(this.program,compile(g.VERTEX_SHADER,vs));g.attachShader(this.program,compile(g.FRAGMENT_SHADER,fs));g.linkProgram(this.program);if(!g.getProgramParameter(this.program,g.LINK_STATUS))throw Error(g.getProgramInfoLog(this.program));g.useProgram(this.program);this.buffer=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.buffer);let off=0;for(let [name,n]of [['aPos',3],['aNormal',3],['aColor',3],['aEx',3],['aId',1]]){let loc=g.getAttribLocation(this.program,name);g.enableVertexAttribArray(loc);g.vertexAttribPointer(loc,n,g.FLOAT,false,52,off);off+=n*4;}
 this.uVP=g.getUniformLocation(this.program,'uVP');this.uEx=g.getUniformLocation(this.program,'uExplode');this.uSel=g.getUniformLocation(this.program,'uSelected');g.enable(g.DEPTH_TEST);g.disable(g.CULL_FACE);g.clearColor(.033,.060,.093,1);
 }
 resize(){let r=this.canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.5);this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);if(this.canvas.width!==Math.round(this.width*d)||this.canvas.height!==Math.round(this.height*d)){this.canvas.width=Math.round(this.width*d);this.canvas.height=Math.round(this.height*d);}}
 setScene(scene,keepCamera=false){this.scene=scene;this.target=scene.target;this.selected=0;if(!keepCamera){this.yaw=.67;this.pitch=.52;this.distance=scene.extent;this.explode=this.wantExplode;}if(this.gl){let g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,this.buffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(scene.vertices),g.STATIC_DRAW);}this.labelLayer.innerHTML='';this.labelSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');this.labelSvg.setAttribute('class','label-leaders');this.labelLayer.appendChild(this.labelSvg);this.labelNodes=[];let counts=new Set();for(let p of scene.labels){const labelKey=p.resource+':'+p.name;if(counts.has(labelKey))continue;counts.add(labelKey);let b=document.createElement('button');b.className='part-label';b.textContent=p.name||p.resource;b.title='查看 '+b.textContent;b.onclick=()=>this.onPick(p.resource,p.name);this.labelLayer.appendChild(b);let line=document.createElementNS('http://www.w3.org/2000/svg','polyline'),dot=document.createElementNS('http://www.w3.org/2000/svg','circle');line.setAttribute('fill','none');line.setAttribute('stroke','#6b98a8');line.setAttribute('stroke-width','.8');line.setAttribute('opacity','.7');dot.setAttribute('r','2');dot.setAttribute('fill','#89bac3');this.labelSvg.appendChild(line);this.labelSvg.appendChild(dot);this.labelNodes.push({p,b,line,dot});}this.dirty=true;}
 zoom(ratio){this.distance=Math.min(95,Math.max(3,this.distance*ratio));this.dirty=true;}
 setExplosion(v){this.wantExplode=v;this.dirty=true;}
 view(name){if(name==='top'){this.pitch=1.46;this.yaw=0;}else if(name==='front'){this.pitch=.16;this.yaw=0;}else{this.pitch=.52;this.yaw=.67;this.distance=this.scene.extent;}this.dirty=true;}
 position(p){return V3.add(p.pos,V3.mul(p.ex,this.explode));}
 project(p){let m=this.vp,[x,y,z]=p,ww=m[3]*x+m[7]*y+m[11]*z+m[15];if(ww<=0)return null;return [(m[0]*x+m[4]*y+m[8]*z+m[12])/ww*this.width/2+this.width/2,-(m[1]*x+m[5]*y+m[9]*z+m[13])/ww*this.height/2+this.height/2,(m[2]*x+m[6]*y+m[10]*z+m[14])/ww];}
 camera(){let eye=V3.add(this.target,[this.distance*Math.cos(this.pitch)*Math.sin(this.yaw),this.distance*Math.sin(this.pitch),this.distance*Math.cos(this.pitch)*Math.cos(this.yaw)]);this.eye=eye;this.vp=m4mul(perspective(.70,this.width/this.height,.05,250),lookAt(eye,this.target));}
 pick(x,y){if(!this.scene)return;this.camera();let forward=V3.norm(V3.sub(this.target,this.eye)),right=V3.norm(V3.cross(forward,[0,1,0])),up=V3.cross(right,forward),t=Math.tan(.35);let dir=V3.norm(V3.add(forward,V3.add(V3.mul(right,(x/this.width*2-1)*t*this.width/this.height),V3.mul(up,(1-y/this.height*2)*t))));let best=null,bestT=Infinity;for(let p of this.scene.parts){if(!p.resource||p.pick===false)continue;let pos=this.position(p),lo=0,hi=Infinity;for(let j=0;j<3;j++){let min=pos[j]-p.size[j]/2,max=pos[j]+p.size[j]/2;if(Math.abs(dir[j])<1e-8){if(this.eye[j]<min||this.eye[j]>max){hi=-1;break;}}else{let a=(min-this.eye[j])/dir[j],b=(max-this.eye[j])/dir[j];lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b));}}if(hi>=lo&&lo<bestT){best=p;bestT=lo;}}if(best){this.selected=best.id;this.dirty=true;this.onPick(best.resource,best.name);}}
 drawLabels(){const mobile=this.width<550,limit=mobile?4:8;let boxes=[];for(let [i,{p,b,line,dot}] of this.labelNodes.entries()){line.style.display='none';dot.style.display='none';if(i>=limit){b.hidden=true;continue;}let point=this.project(this.position(p));if(!point||point[2]>1){b.hidden=true;continue;}b.hidden=false;let w=Math.min(b.offsetWidth||130,this.width-30),h=b.offsetHeight||30;let px=point[0],py=point[1],found=null;let offsets=[[16,-h-13],[16,12],[-w-16,-h-13],[-w-16,12],[16,-h-55],[-w-16,-h-55],[16,53],[-w-16,53]];
 for(let [dx,dy] of offsets){let l=Math.max(12,Math.min(this.width-w-12,px+dx)),top=Math.max(50,Math.min(this.height-h-60,py+dy));if(!boxes.some(q=>l<q[0]+q[2]+8&&l+w+8>q[0]&&top<q[1]+q[3]+8&&top+h+8>q[1])){found=[l,top,w,h];break;}}
 if(!found){b.hidden=true;continue;}boxes.push(found);b.style.left=found[0]+'px';b.style.top=found[1]+'px';b.style.setProperty('--part-color',p.col);let endX=Math.max(found[0],Math.min(found[0]+w,px)),endY=Math.max(found[1],Math.min(found[1]+h,py));line.setAttribute('points',`${px},${py} ${px},${endY} ${endX},${endY}`);line.style.display='';dot.setAttribute('cx',px);dot.setAttribute('cy',py);dot.style.display='';}
 }
 drawFallback(){
  const scale=Math.min(1,1000/this.width),W=Math.max(1,Math.round(this.width*scale)),H=Math.max(1,Math.round(this.height*scale));
  if(!this.soft||this.soft.W!==W||this.soft.H!==H){let cv=document.createElement('canvas');cv.width=W;cv.height=H;let cx=cv.getContext('2d'),im=cx.createImageData(W,H);this.soft={W,H,cv,cx,im,pix:new Uint32Array(im.data.buffer),z:new Float32Array(W*H)};}
  const soft=this.soft,pix=soft.pix,depth=soft.z;pix.fill(0xff180f08);depth.fill(Infinity);
  const data=this.scene.vertices,m=this.vp,ex=this.explode;
  for(let i=0;i<data.length;i+=39){let v=[],bad=false;for(let j=0;j<3;j++){let k=i+j*13,x=data[k]+data[k+9]*ex,y=data[k+1]+data[k+10]*ex,z=data[k+2]+data[k+11]*ex,ww=m[3]*x+m[7]*y+m[11]*z+m[15];if(ww<=0){bad=true;break;}v.push([(m[0]*x+m[4]*y+m[8]*z+m[12])/ww*W/2+W/2,-(m[1]*x+m[5]*y+m[9]*z+m[13])/ww*H/2+H/2,(m[2]*x+m[6]*y+m[10]*z+m[14])/ww]);}if(bad)continue;
   let [[x0,y0,z0],[x1,y1,z1],[x2,y2,z2]]=v,area=(x1-x0)*(y2-y0)-(y1-y0)*(x2-x0);if(Math.abs(area)<.08)continue;
   if(area<0){[x1,x2]=[x2,x1];[y1,y2]=[y2,y1];[z1,z2]=[z2,z1];area=-area;}
   let minX=Math.max(0,Math.floor(Math.min(x0,x1,x2))),maxX=Math.min(W-1,Math.ceil(Math.max(x0,x1,x2))),minY=Math.max(0,Math.floor(Math.min(y0,y1,y2))),maxY=Math.min(H-1,Math.ceil(Math.max(y0,y1,y2)));if(maxX<minX||maxY<minY)continue;
   let A0=y1-y2,B0=x2-x1,C0=x1*y2-x2*y1,A1=y2-y0,B1=x0-x2,C1=x2*y0-x0*y2,A2=y0-y1,B2=x1-x0,C2=x0*y1-x1*y0;
   let nz=data[i+5],ny=data[i+4],nx=data[i+3],light=.47+.46*Math.max(0,nx*(-.46)+ny*.75+nz*.50)+.15*Math.max(0,nx*.74+ny*.42-nz*.53);let rr=data[i+6],gg=data[i+7],bb=data[i+8];if(this.selected&&data[i+12]===this.selected){rr=rr*.58+.98*.42;gg=gg*.58+.73*.42;bb=bb*.58+.33*.42;}let col=(255<<24)|(Math.min(255,Math.round(bb*light*255))<<16)|(Math.min(255,Math.round(gg*light*255))<<8)|Math.min(255,Math.round(rr*light*255));
   let inv=1/area,dzdx=(A0*z0+A1*z1+A2*z2)*inv;
   for(let y=minY;y<=maxY;y++){let xx=minX+.5,yy=y+.5,w0=A0*xx+B0*yy+C0,w1=A1*xx+B1*yy+C1,w2=A2*xx+B2*yy+C2,z=(w0*z0+w1*z1+w2*z2)*inv,idx=y*W+minX;for(let x=minX;x<=maxX;x++,idx++,w0+=A0,w1+=A1,w2+=A2,z+=dzdx){if(w0>=-.001&&w1>=-.001&&w2>=-.001&&z<depth[idx]){depth[idx]=z;pix[idx]=col;}}}
  }
  soft.cx.putImageData(soft.im,0,0);this.ctx.drawImage(soft.cv,0,0,this.canvas.width,this.canvas.height);
 }
 render(){if(!this.scene)return;this.camera();if(this.gl){let g=this.gl;g.viewport(0,0,this.canvas.width,this.canvas.height);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.uniformMatrix4fv(this.uVP,false,new Float32Array(this.vp));g.uniform1f(this.uEx,this.explode);g.uniform1f(this.uSel,this.selected);g.drawArrays(g.TRIANGLES,0,this.scene.vertices.length/13);}else this.drawFallback();this.drawLabels();}
 loop(){let tick=()=>{if(Math.abs(this.explode-this.wantExplode)>.002){this.explode=this.reduced?this.wantExplode:this.explode+(this.wantExplode-this.explode)*.18;this.dirty=true;}if(this.dirty){this.render();this.dirty=false;}requestAnimationFrame(tick);};requestAnimationFrame(tick);}
}
